const funnyNames = [
    "Al Beback",
    "Anita Bath",
    "Barb Dwyer",
    "Ben Dover",
    "Bill Board",
    "Bob Upndown",
    "Brock Lee",
    "Bud Light",
    "Cindy Rella",
    "Dewey Cheatem",
    "Dixie Normous",
    "Ella Vator",
    "Ernie Me",
    "Eileen Dover",
    "Frank N. Stein",
    "Gail Forcewind",
    "Hal Jalikee",
    "Harry Butts",
    "Hugh Jass",
    "Iona Trailer",
    "Justin Time",
    "Kerry Oki",
    "Lois Price",
    "Lou Natic",
    "Luke Warm",
    "Moe Lester",
    "Neil Down",
    "Olive Yew",
    "Paige Turner",
    "Pat Myback",
    "Peg Leg",
    "Phil McCracken",
    "Ray Gunn",
    "Rick O'Shea",
    "Robin Banks",
    "Russ T. Nailz",
    "Sal Ami",
    "Sandy Beach",
    "Saul T. Balls",
    "Sue Flay",
    "Tara Misu",
    "Tim Burr",
    "Tina Tally",
    "Tom Foolery",
    "Tyrone Shoe",
    "Warren Peace",
    "Will Power",
    "Willy Stroker",
    "Woody Johnson",
    "Yuri Nator",
    "Zelda Sauce",
    "Ella Mental",
    "Justin Case",
    "Ivana Tinkle",
    "Chris P. Bacon",
    "Barry Cuda",
    "Anna Sthesia",
    "Lana Backwards",
    "Al Bumen",
    "Buster Hyman",
    "Crystal Clear",
    "Drew Peacock",
    "Fanny Pack",
    "Gabe Asparagus",
    "Holly Wood",
    "Jimmy Changa",
    "Karl Dingus",
    "Manny Jahs",
    "Ned Sheeran",
    "Oprah Windfury",
    "Penny Loafer",
    "Queenie Toots",
    "Rita Book",
    "Seymour Butts",
    "Ted E. Bear",
    "Upton O’Goode",
    "Val Crow",
    "Wendy Whoppers",
    "Yul B. Sorry",
    "Zane L. Beers",
    "Bea O'Problem",
    "Doug Hole",
    "Ella Phantz",
    "Izzy Dead",
    "Lotta Nerve",
    "Noah Fence",
    "Omar Gosh",
    "Reed A. Book",
    "Stan Still",
    "Trudy Light",
    "Willie Makit",
    "Al Dente",
    "Art Major",
    "Cam L. Toe",
    "Don Keigh",
    "Felix Cited",
    "Gil T. Azell",
    "Hugh G. Rection",
    "Les Ismore",
    "Max Volume",
    "Nina Nother",
    "Opal Ring",
    "Rusty Pipes",
    "Scott Free"
  ];
export default funnyNames;  